dist: xenial
sudo: required
language: python
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35

install:
- pip install tox
script: tox -e $TOX_ENV
after_success:
- pip install coveralls
- coveralls
