dist: xenial
sudo: required
language: python

services:
  - docker

before_install:
  - docker pull toucantoco/backtechtest
  - docker run -d --rm -i -p 27017:27017 toucantoco/backtechtest
  
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37

install:
- pip install -r requirements-tests.txt
script: tox -e $TOX_ENV

# Push the results back to codecov
after_success:
- codecov