openapi: "3.0.0"
info:
  version: 0.0.1
  title: My Toucan Toco demo project
  license:
    name: Apache-2.0
paths:
  /queries:
    post:
      summary: Create the queries from a CSON configuration file and return a safe CSON
      operationId: tt_demo.create_queries_from_cson
      tags:
        - queries
      requestBody:
        description: A CSON configuration file
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: The CSON configuration file with query ids instead of descriptions.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: List all queries
      operationId: tt_demo.list_queries
      tags:
        - queries
      responses:
        '200':
          description: An array of query ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryID"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /query/{query_id}:
    get:
      summary: Get the query description
      operationId: tt_demo.get_query
      tags:
        - queries
      parameters:
        - name: query_id
          in: path
          required: true
          description: The id of the query to retrieve
          schema:
            $ref: "#/components/schemas/QueryID"
      responses:
        '200':
          description: The expected query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Query"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /mycoll/query:
    post:
      summary: Get mycoll data 
      operationId: tt_demo.query
      tags:
        - mycoll
      parameters:
        - name: id
          in: query
          required: true
          description: The id of the query to execute
          schema:
            $ref: "#/components/schemas/QueryID"
      requestBody:
        description: A filter
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryFilter'            
      responses:
        '200':
          description: The result of the query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryResult"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    QueryID:
      type: string
      readOnly: true
      example: "61dbb89ca5de54506143f3a7a07c2763"
    Query:
      required:
        - id
        - description
      properties:
        id:
          $ref: "#/components/schemas/QueryID"
        description:
          type: string
          example: '{"domain": "test_domain_2", "my_key": "{{filter}}"}'
    QueryFilter:
      type: object
      example: {"filter" : "2017"}
    QueryResult:
      type: array
      format: object
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
